name: ml'


          core: true
          cask: false
          test-bot: false

      - name: Set up actionlint
        shell: bash
        env:
          HOMEBREW_TAP_REPOSITORY: ${{ steps.setup-homebrew.outputs.repository-path }}
        run: |
          brew install actionlint shellcheck

          # Annotations work only relative to GITHUB_WORKSPACE
          (shopt -s dotglob; rm -rf "${GITHUB_WORKSPACE:?}"/*; mv "${HOMEBREW_TAP_REPOSITORY:?}"/* "$GITHUB_WORKSPACE")
          rmdir "$HOMEBREW_TAP_REPOSITORY"
          ln -vs "$GITHUB_WORKSPACE" "$HOMEBREW_TAP_REPOSITORY"

          # Setting `shell: /bin/bash` prevents shellcheck from running on
          # those steps, so let's change them to `shell: bash` for linting.
          sed -i 's:/bin/bash -e {0}:bash:' .github/workflows/*.y*ml
          # The JSON matcher needs to be accessible to the container host.
          cp "$(brew --repository)/.github/actionlint-matcher.json" "$HOME"
          echo "::add-matcher::$HOME/actionlint-matcher.json"

      - run: actionlint
